In [ ]:
# prompt: کد شبکه عصبی مصنوعی بده

import tensorflow as tf

# تعریف مدل
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])

# کامپایل مدل
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# آموزش مدل
model.fit(x_train, y_train, epochs=10)

# ارزیابی مدل
loss, accuracy = model.evaluate(x_test,  y_test, verbose=2)
print('Loss:', loss)
print('Accuracy:', accuracy)


**Tensorflow**

In [1]:
import tensorflow as tf

**data structures**

In [2]:
# adad= bedone boad
a=tf.constant(1)
a

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [3]:
b=tf.constant([1,2])
b
# bordar 1 boad ast

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
c=tf.constant([[1,2,3],[4,5,6]])
#matris 2boadi ast
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [6]:
d=tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

**Diffent operations**

In [8]:
a=tf.constant([1,2])
b=tf.constant([3,4])
c=tf.add(a,b)
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [9]:
d=tf.subtract(a,b)
d.numpy()

array([-2, -2], dtype=int32)

In [10]:
e=tf.multiply(a,b)
e.numpy()

array([3, 8], dtype=int32)

In [17]:
a = tf.constant([[1,2]])  # Reshape to a 2D tensor
b = tf.constant([[3],[4]])  # Reshape to a 2D tensor with 2 rows and 1 column
f = tf.matmul(a, b)
f

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[11]], dtype=int32)>

**reshape**

In [18]:
a=tf.constant([1,2,3,4])
a.shape

TensorShape([4])

In [19]:
b=tf.reshape(a,shape=(2,2))
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [20]:
#operations
x=tf.constant([[1,2],[3,4]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [22]:
b=tf.square(x)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [23]:
#min/max
y=tf.constant([[1,2],[3,4]])
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [26]:
max=tf.reduce_max(y)
max.numpy()

4